### ISSUE TITLE
Build failed with config.package_name.in.h

### ISSUE THREAD

**Issue by dhs227** [xchataqua/xchataqua#197]
I synced the latest code and did what Wiki page said, there is an build error saying:
> ...xchataqua/xchat/config.h:419:10: 'config.package_name.in.h' file not found

My build environment is OS X El Capitan 10.11.2  Xcode 7.2 (7C68)

**Comment by youknowone** [comment]
I expect the file is generated during build process.

The content is
```
/* Define to the full name and version of this package. */
#define PACKAGE_STRING "XChat 2.8.8-svn1523"

/* Define to the version of this package. */
#define PACKAGE_VERSION "2.8.8-svn1523"
```

**Comment by dhs227** [comment]
Thank you! Can you also let me know in what step it is expected to be generated? So I want to look into it to see if anything goes wrong with it.

**Comment by youknowone** [comment]
If you run `Prebuild` target, there are 3 steps to prepare the build environment.

1. Generate XChat Package Name
this phase runs `"tools/gen_xchat_package_name.sh" > "xchat/config.package_name.in.h"`
(This step is expected to do it)

2. Generate build number
This phase generates build version from git tags

3. Generate localization files.
Because xchat azure localization is using legacy localization system, instead of Base.lproj, it is using a bunch of .xib files by locales.
This step generate .xib files from xchat localization files and xchat azure english .xib files.

**Comment by dhs227** [comment]
Thank you very much youknowone for the explanation.

**Comment by youknowone** [comment]
So you could build it finally? :)
