### ISSUE TITLE
 iOS APP

### ISSUE THREAD

**Issue by hanxi259** [xchataqua/xchataqua#269]
Hello, I am an iOS developer. I see your iOS APP and am interested in it. Are you interested in selling this APP?
I'm going to buy your APP, how much do you want to sell it for?

If you are interested in selling, please contact me.
Skype: live:1181040659
Email address: hanxi259@gmail.com

**Comment by youknowone** [comment]
Hello. This is a GPL licensed project. It means you can use the code free unless you also distribute your code under same version of GPL.

Because you made exact same comment to very different project, I decide not to take your suggestion very seroius at this stage
( https://github.com/dddiehard21/currency-exchange/issues/1 )

If you are actually an iOS developer, you can find my email in the git history. So please Contact me there.
